"""google sign-in

Revision ID: 19163701a1f6
Revises: 0fe65019d0d8
Create Date: 2026-09-26 09:03:48.736987

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19163701a1f6"
down_revision: str | Sequence[str] | None = "0fe65019d0d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_sub", sa.String(length=255), nullable=True))
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.create_index(op.f("ix_users_google_sub"), "users", ["google_sub"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_sub"), table_name="users")
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("users", "google_sub")
    # ### end Alembic commands ###
