"""resume profile

Revision ID: dee383a78a3d
Revises: a7acfd74caf1
Create Date: 2026-09-25 02:19:45.320509

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dee383a78a3d"
down_revision: str | Sequence[str] | None = "a7acfd74caf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("resume_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "sessions",
        sa.Column(
            "resume_profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "resume_profile")
    op.drop_column("profiles", "resume_hash")
    # ### end Alembic commands ###
