"""queue position

Revision ID: 0fe65019d0d8
Revises: c6cfce6a1762
Create Date: 2026-09-25 23:48:36.413094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe65019d0d8'
down_revision: Union[str, Sequence[str], None] = 'c6cfce6a1762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_items', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_items', 'position')
    # ### end Alembic commands ###
